apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  labels:
    app: myapp
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: europe-west4-docker.pkg.dev/k8-cluster-470912/blue-green-app/green@sha256:00382d301f77e3a304d223bf9733d807b5e25a82dcd53d9418e115c84d0dfc36
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gar-secret
