apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
    version: green   # 🔄 verander naar "green" om over te schakelen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080