name: Deploy Blue to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: k8-cluster-470912
  REGION: europe-west4
  CLUSTER: bluegreen-cluster
  REPOSITORY: blue-green-app
  DEPLOYMENT_FILE: deploy-blue.yml
  IMAGE_NAME: blue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Configure gcloud
      run: |
        gcloud config set project $PROJECT_ID
        gcloud config set compute/region $REGION

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
        gcloud components update

    - name: Get GKE credentials
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials $CLUSTER --region $REGION

    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        kubectl apply -f $DEPLOYMENT_FILE
        kubectl set image deployment/blue-deployment blue=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}
