name: Deploy Green to GKE

on:
  push:
    branches:
      - test

env:
  PROJECT_ID: k8-cluster-470912
  REGION: europe-west4
  CLUSTER: bluegreen-cluster
  REPOSITORY: blue-green-app
  DEPLOYMENT_FILE: deploy-green.yml
  IMAGE_NAME: green

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Docker login to Artifact Registry
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$REGION-docker.pkg.dev

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.CLUSTER }}
        location: ${{ env.REGION }}

    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f $DEPLOYMENT_FILE
        kubectl get pods
